on:
    push:
        branches:
            - top3host
name: 🚀 Deploy to top3 host
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.TOP3_HOST }}
        username: ${{ secrets.TOP3_USER }}
        password: ${{ secrets.TOP3_PASSWORD }}
        server-dir: /
