on:
    push:
        branches:
            - main
name: 🚀 Deploy from main
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.INFINITY_FREE_HOST }}
        username: ${{ secrets.INFINITY_FREE_USER }}
        password: ${{ secrets.INFINITY_FREE_PASSWORD }}
        server-dir: /cleanerp.free.nf/
